name: auth
description: "A new Flutter package project."
version: 0.0.1
homepage: "https://github.com/kaimono-plus/kaimono-plus"

environment:
  sdk: ^3.10.3

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: {}
