name: auth
description: "A new Flutter package project."
version: 0.0.1
homepage: "https://github.com/kaimono-plus/kaimono-plus"

environment:
  sdk: ^3.10.3

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  altive_lints: ^2.1.0
  flutter_test:
    sdk: flutter

flutter: {}
