name: kaimono_plus_workspace
publish_to: none
environment:
  sdk: ^3.10.3

workspace:
  - packages/apps/kaimono_plus
  - packages/core/auth
dev_dependencies:
  melos: ^7.4.0
dependencies:
  altive_lints: ^2.1.0
  clock: ^1.1.2

dependency_overrides:
  test_api: ^0.7.8
