name: kaimono_plus
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.3

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.1
  gap: ^3.0.1
  auth:
    path: ../../core/auth
  hooks_riverpod: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_lint: ^3.0.0-dev.4

flutter:
  uses-material-design: true
