name: kaimono_plus
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.3

resolution: workspace

dependencies:
  auth:
    path: ../../core/auth
  design_system:
    path: ../../design_system
  flutter:
    sdk: flutter
  gap: ^3.0.1
  hooks_riverpod: ^3.2.1
  provider: ^6.1.1
  riverpod_lint: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
